// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqcZRsdwKYyMITmUbaHfUKkdM4ojBdM8A',
    appId: '1:223549102544:web:dea3fe6de8959f1d7a41d5',
    messagingSenderId: '223549102544',
    projectId: 'mycareer-f3f24',
    authDomain: 'mycareer-f3f24.firebaseapp.com',
    storageBucket: 'mycareer-f3f24.firebasestorage.app',
    measurementId: 'G-FRTBWYT6V7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCouduBgIZmZm10ow1pGCUbodqc5PxNoVw',
    appId: '1:223549102544:android:1de7acd266e8ce747a41d5',
    messagingSenderId: '223549102544',
    projectId: 'mycareer-f3f24',
    storageBucket: 'mycareer-f3f24.firebasestorage.app',
  );
}
